/********************************************************************
* dicts/Linux64RHEL7/TCCPBClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TCCPBClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTCCPBClassDict();
extern void G__cpp_setup_inheritanceTCCPBClassDict();
extern void G__cpp_setup_typetableTCCPBClassDict();
extern void G__cpp_setup_memvarTCCPBClassDict();
extern void G__cpp_setup_globalTCCPBClassDict();
extern void G__cpp_setup_memfuncTCCPBClassDict();
extern void G__cpp_setup_funcTCCPBClassDict();
extern void G__set_cpp_environmentTCCPBClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TCCPBClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TCCPBClassDictLN_TClass;
extern G__linked_taginfo G__TCCPBClassDictLN_TBuffer;
extern G__linked_taginfo G__TCCPBClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TCCPBClassDictLN_TObject;
extern G__linked_taginfo G__TCCPBClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TCCPBClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCCPBClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TCCPBClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TCCPBClassDictLN_TCCPBClass;

/* STUB derived class for protected member access */
