/********************************************************************
* dicts/Linux64RHEL7/TGSIMClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TGSIMClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGSIMClassDict();
extern void G__cpp_setup_inheritanceTGSIMClassDict();
extern void G__cpp_setup_typetableTGSIMClassDict();
extern void G__cpp_setup_memvarTGSIMClassDict();
extern void G__cpp_setup_globalTGSIMClassDict();
extern void G__cpp_setup_memfuncTGSIMClassDict();
extern void G__cpp_setup_funcTGSIMClassDict();
extern void G__set_cpp_environmentTGSIMClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGSIMClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGSIMClassDictLN_TClass;
extern G__linked_taginfo G__TGSIMClassDictLN_TBuffer;
extern G__linked_taginfo G__TGSIMClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TGSIMClassDictLN_TObject;
extern G__linked_taginfo G__TGSIMClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGSIMClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGSIMClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGSIMClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGSIMClassDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGSIMClassDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGSIMClassDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGSIMClassDictLN_TVirtualData;
extern G__linked_taginfo G__TGSIMClassDictLN_TGSIMClass;

/* STUB derived class for protected member access */
