/********************************************************************
* dicts/Linux64RHEL7/TS1STClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TS1STClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTS1STClassDict();
extern void G__cpp_setup_inheritanceTS1STClassDict();
extern void G__cpp_setup_typetableTS1STClassDict();
extern void G__cpp_setup_memvarTS1STClassDict();
extern void G__cpp_setup_globalTS1STClassDict();
extern void G__cpp_setup_memfuncTS1STClassDict();
extern void G__cpp_setup_funcTS1STClassDict();
extern void G__set_cpp_environmentTS1STClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TS1STClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TS1STClassDictLN_TClass;
extern G__linked_taginfo G__TS1STClassDictLN_TBuffer;
extern G__linked_taginfo G__TS1STClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TS1STClassDictLN_TObject;
extern G__linked_taginfo G__TS1STClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TS1STClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TS1STClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TS1STClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TS1STClassDictLN_TS1STClass;

/* STUB derived class for protected member access */
