/********************************************************************
* dicts/Linux64RHEL7/TSTPBClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TSTPBClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTSTPBClassDict();
extern void G__cpp_setup_inheritanceTSTPBClassDict();
extern void G__cpp_setup_typetableTSTPBClassDict();
extern void G__cpp_setup_memvarTSTPBClassDict();
extern void G__cpp_setup_globalTSTPBClassDict();
extern void G__cpp_setup_memfuncTSTPBClassDict();
extern void G__cpp_setup_funcTSTPBClassDict();
extern void G__set_cpp_environmentTSTPBClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TSTPBClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TSTPBClassDictLN_TClass;
extern G__linked_taginfo G__TSTPBClassDictLN_TBuffer;
extern G__linked_taginfo G__TSTPBClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TSTPBClassDictLN_TObject;
extern G__linked_taginfo G__TSTPBClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TSTPBClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSTPBClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TSTPBClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TSTPBClassDictLN_TSTPBClass;

/* STUB derived class for protected member access */
