//
// File generated by /u/apps/root/5.34.36/root/bin/rootcint at Fri Feb 24 17:38:09 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinux64RHEL7dITTAGRClassDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TTAGRClassDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ROOTDict {
   void TTAGRClass_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TTAGRClass(void *p = 0);
   static void *newArray_TTAGRClass(Long_t size, void *p);
   static void delete_TTAGRClass(void *p);
   static void deleteArray_TTAGRClass(void *p);
   static void destruct_TTAGRClass(void *p);
   static void streamer_TTAGRClass(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TTAGRClass*)
   {
      ::TTAGRClass *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TTAGRClass >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TTAGRClass", ::TTAGRClass::Class_Version(), "./TTAGRClass.h", 16,
                  typeid(::TTAGRClass), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TTAGRClass::Dictionary, isa_proxy, 0,
                  sizeof(::TTAGRClass) );
      instance.SetNew(&new_TTAGRClass);
      instance.SetNewArray(&newArray_TTAGRClass);
      instance.SetDelete(&delete_TTAGRClass);
      instance.SetDeleteArray(&deleteArray_TTAGRClass);
      instance.SetDestructor(&destruct_TTAGRClass);
      instance.SetStreamerFunc(&streamer_TTAGRClass);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TTAGRClass*)
   {
      return GenerateInitInstanceLocal((::TTAGRClass*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TTAGRClass*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TTAGRClass::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TTAGRClass::Class_Name()
{
   return "TTAGRClass";
}

//______________________________________________________________________________
const char *TTAGRClass::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TTAGRClass*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TTAGRClass::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TTAGRClass*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TTAGRClass::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TTAGRClass*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TTAGRClass::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TTAGRClass*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TTAGRClass::Streamer(TBuffer &R__b)
{
   // Stream an object of class TTAGRClass.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> ERG;
      R__b >> TTAG;
      R__b >> TPHO;
      R__b >> STAT;
      R__b >> T_id;
      R__b >> E_id;
      R__b.CheckByteCount(R__s, R__c, TTAGRClass::IsA());
   } else {
      R__c = R__b.WriteVersion(TTAGRClass::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << ERG;
      R__b << TTAG;
      R__b << TPHO;
      R__b << STAT;
      R__b << T_id;
      R__b << E_id;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TTAGRClass::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TTAGRClass.
      TClass *R__cl = ::TTAGRClass::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "ERG", &ERG);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TTAG", &TTAG);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "TPHO", &TPHO);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "STAT", &STAT);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "T_id", &T_id);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "E_id", &E_id);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TTAGRClass(void *p) {
      return  p ? new(p) ::TTAGRClass : new ::TTAGRClass;
   }
   static void *newArray_TTAGRClass(Long_t nElements, void *p) {
      return p ? new(p) ::TTAGRClass[nElements] : new ::TTAGRClass[nElements];
   }
   // Wrapper around operator delete
   static void delete_TTAGRClass(void *p) {
      delete ((::TTAGRClass*)p);
   }
   static void deleteArray_TTAGRClass(void *p) {
      delete [] ((::TTAGRClass*)p);
   }
   static void destruct_TTAGRClass(void *p) {
      typedef ::TTAGRClass current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TTAGRClass(TBuffer &buf, void *obj) {
      ((::TTAGRClass*)obj)->::TTAGRClass::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TTAGRClass

/********************************************************
* dicts/Linux64RHEL7/TTAGRClassDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTTAGRClassDict();

extern "C" void G__set_cpp_environmentTTAGRClassDict() {
  G__cpp_reset_tagtableTTAGRClassDict();
}
#include <new>
extern "C" int G__cpp_dllrevTTAGRClassDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TTAGRClass */
static int G__TTAGRClassDict_184_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTAGRClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTAGRClass[n];
     } else {
       p = new((void*) gvp) TTAGRClass[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TTAGRClass;
     } else {
       p = new((void*) gvp) TTAGRClass;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTAGRClass* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TTAGRClass((TTAGRClass*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TTAGRClass((TTAGRClass*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TTAGRClass*) G__getstructoffset())->GetEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TTAGRClass*) G__getstructoffset())->GetTagTime());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TTAGRClass*) G__getstructoffset())->GetTagRF());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TTAGRClass*) G__getstructoffset())->GetStat());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TTAGRClass*) G__getstructoffset())->GetTid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TTAGRClass*) G__getstructoffset())->GetEid());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTAGRClass*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TTAGRClass::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTAGRClass::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TTAGRClass::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TTAGRClass::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TTAGRClass*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTAGRClass::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TTAGRClass::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TTAGRClass::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TTAGRClassDict_184_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TTAGRClass::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TTAGRClassDict_184_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TTAGRClass* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TTAGRClass(*(TTAGRClass*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TTAGRClass G__TTTAGRClass;
static int G__TTAGRClassDict_184_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TTAGRClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TTAGRClass*) (soff+(sizeof(TTAGRClass)*i)))->~G__TTTAGRClass();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TTAGRClass*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TTAGRClass*) (soff))->~G__TTTAGRClass();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TTAGRClassDict_184_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TTAGRClass* dest = (TTAGRClass*) G__getstructoffset();
   *dest = *(TTAGRClass*) libp->para[0].ref;
   const TTAGRClass& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TTAGRClass */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTTAGRClassDict {
 public:
  G__Sizep2memfuncTTAGRClassDict(): p(&G__Sizep2memfuncTTAGRClassDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTTAGRClassDict::*p)();
};

size_t G__get_sizep2memfuncTTAGRClassDict()
{
  G__Sizep2memfuncTTAGRClassDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTTAGRClassDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass))) {
     TTAGRClass *G__Lderived;
     G__Lderived=(TTAGRClass*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass),G__get_linked_tagnum(&G__TTAGRClassDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTTAGRClassDict() {

   /* Setting up typedef entry */
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TTAGRClass */
static void G__setup_memvarTTAGRClass(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass));
   { TTAGRClass *p; p=(TTAGRClass*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->ERG)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"ERG=",0,"Energy of the photon in GeV");
   G__memvar_setup((void*)((long)(&p->TTAG)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TTAG=",0,"Time of the photon has reconstructed in the Tagger");
   G__memvar_setup((void*)((long)(&p->TPHO)-(long)(p)),102,0,0,-1,G__defined_typename("Float_t"),-1,1,"TPHO=",0,"Time of the photon after RF correction");
   G__memvar_setup((void*)((long)(&p->STAT)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"STAT=",0,"Status ( 7 or 15 are Good) other values have problems (see tag_process_TAGR.F) ");
   G__memvar_setup((void*)((long)(&p->T_id)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"T_id=",0,"T counter Id");
   G__memvar_setup((void*)((long)(&p->E_id)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"E_id=",0,"E counter Id");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TTAGRClassDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTTAGRClassDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTTAGRClass(void) {
   /* TTAGRClass */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass));
   G__memfunc_setup("TTAGRClass",888,G__TTAGRClassDict_184_0_1, 105, G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TTAGRClass",888,G__TTAGRClassDict_184_0_2, 105, G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass), -1, 0, 1, 1, 1, 0, "U 'TTAGRClass' - 0 - TmpSTPB", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEnergy",906,G__TTAGRClassDict_184_0_3, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTagTime",971,G__TTAGRClassDict_184_0_4, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTagRF",724,G__TTAGRClassDict_184_0_5, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetStat",700,G__TTAGRClassDict_184_0_6, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetTid",577,G__TTAGRClassDict_184_0_7, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEid",562,G__TTAGRClassDict_184_0_8, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__TTAGRClassDict_184_0_9, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TTAGRClassDict_184_0_10, 85, G__get_linked_tagnum(&G__TTAGRClassDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TTAGRClass::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TTAGRClassDict_184_0_11, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTAGRClass::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TTAGRClassDict_184_0_12, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TTAGRClass::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TTAGRClassDict_184_0_13, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TTAGRClass::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TTAGRClassDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TTAGRClassDict_184_0_17, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TTAGRClassDict_184_0_18, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTAGRClass::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TTAGRClassDict_184_0_19, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TTAGRClass::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TTAGRClassDict_184_0_20, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TTAGRClass::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TTAGRClassDict_184_0_21, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TTAGRClass::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TTAGRClass", 888, G__TTAGRClassDict_184_0_22, (int) ('i'), G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass), -1, 0, 1, 1, 1, 0, "u 'TTAGRClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TTAGRClass", 1014, G__TTAGRClassDict_184_0_23, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TTAGRClassDict_184_0_24, (int) ('u'), G__get_linked_tagnum(&G__TTAGRClassDictLN_TTAGRClass), -1, 1, 1, 1, 1, 0, "u 'TTAGRClass' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTTAGRClassDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTTAGRClassDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTTAGRClassDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TTAGRClassDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TTAGRClassDictLN_TTAGRClass = { "TTAGRClass" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTTAGRClassDict() {
  G__TTAGRClassDictLN_TClass.tagnum = -1 ;
  G__TTAGRClassDictLN_TBuffer.tagnum = -1 ;
  G__TTAGRClassDictLN_TMemberInspector.tagnum = -1 ;
  G__TTAGRClassDictLN_TObject.tagnum = -1 ;
  G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TTAGRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TTAGRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TTAGRClassDictLN_TTAGRClass.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTTAGRClassDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TTAGRClassDictLN_TTAGRClass),sizeof(TTAGRClass),-1,62720,"Class for accessing the TGPB bank: Tagger",G__setup_memvarTTAGRClass,G__setup_memfuncTTAGRClass);
}
extern "C" void G__cpp_setupTTAGRClassDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTTAGRClassDict()");
  G__set_cpp_environmentTTAGRClassDict();
  G__cpp_setup_tagtableTTAGRClassDict();

  G__cpp_setup_inheritanceTTAGRClassDict();

  G__cpp_setup_typetableTTAGRClassDict();

  G__cpp_setup_memvarTTAGRClassDict();

  G__cpp_setup_memfuncTTAGRClassDict();
  G__cpp_setup_globalTTAGRClassDict();
  G__cpp_setup_funcTTAGRClassDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTTAGRClassDict();
  return;
}
class G__cpp_setup_initTTAGRClassDict {
  public:
    G__cpp_setup_initTTAGRClassDict() { G__add_setup_func("TTAGRClassDict",(G__incsetup)(&G__cpp_setupTTAGRClassDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTTAGRClassDict() { G__remove_setup_func("TTAGRClassDict"); }
};
G__cpp_setup_initTTAGRClassDict G__cpp_setup_initializerTTAGRClassDict;

