/********************************************************************
* dicts/Linux64RHEL7/TTGBIClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TTGBIClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTGBIClassDict();
extern void G__cpp_setup_inheritanceTTGBIClassDict();
extern void G__cpp_setup_typetableTTGBIClassDict();
extern void G__cpp_setup_memvarTTGBIClassDict();
extern void G__cpp_setup_globalTTGBIClassDict();
extern void G__cpp_setup_memfuncTTGBIClassDict();
extern void G__cpp_setup_funcTTGBIClassDict();
extern void G__set_cpp_environmentTTGBIClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTGBIClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTGBIClassDictLN_TClass;
extern G__linked_taginfo G__TTGBIClassDictLN_TBuffer;
extern G__linked_taginfo G__TTGBIClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TTGBIClassDictLN_TObject;
extern G__linked_taginfo G__TTGBIClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTGBIClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTGBIClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTGBIClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTGBIClassDictLN_TTGBIClass;

/* STUB derived class for protected member access */
