/********************************************************************
* dicts/Linux64RHEL7/TVirtualDataDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TVirtualDataDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTVirtualDataDict();
extern void G__cpp_setup_inheritanceTVirtualDataDict();
extern void G__cpp_setup_typetableTVirtualDataDict();
extern void G__cpp_setup_memvarTVirtualDataDict();
extern void G__cpp_setup_globalTVirtualDataDict();
extern void G__cpp_setup_memfuncTVirtualDataDict();
extern void G__cpp_setup_funcTVirtualDataDict();
extern void G__set_cpp_environmentTVirtualDataDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TVirtualData.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TVirtualDataDictLN_TClass;
extern G__linked_taginfo G__TVirtualDataDictLN_TBuffer;
extern G__linked_taginfo G__TVirtualDataDictLN_TMemberInspector;
extern G__linked_taginfo G__TVirtualDataDictLN_TObject;
extern G__linked_taginfo G__TVirtualDataDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TVirtualDataDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualDataDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TVirtualDataDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TVirtualDataDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TVirtualDataDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TVector3;
extern G__linked_taginfo G__TVirtualDataDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TVirtualDataDictLN_TVirtualData;

/* STUB derived class for protected member access */
