/********************************************************************
* dicts/Linux64RHEL7/TVirtualReaderDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TVirtualReaderDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTVirtualReaderDict();
extern void G__cpp_setup_inheritanceTVirtualReaderDict();
extern void G__cpp_setup_typetableTVirtualReaderDict();
extern void G__cpp_setup_memvarTVirtualReaderDict();
extern void G__cpp_setup_globalTVirtualReaderDict();
extern void G__cpp_setup_memfuncTVirtualReaderDict();
extern void G__cpp_setup_funcTVirtualReaderDict();
extern void G__set_cpp_environmentTVirtualReaderDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TVirtualReader.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TVirtualReaderDictLN_TClass;
extern G__linked_taginfo G__TVirtualReaderDictLN_TBuffer;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMemberInspector;
extern G__linked_taginfo G__TVirtualReaderDictLN_TObject;
extern G__linked_taginfo G__TVirtualReaderDictLN_TString;
extern G__linked_taginfo G__TVirtualReaderDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TBrowser;
extern G__linked_taginfo G__TVirtualReaderDictLN_TObjArray;
extern G__linked_taginfo G__TVirtualReaderDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TChain;
extern G__linked_taginfo G__TVirtualReaderDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TVirtualReaderDictLN_TVector3;
extern G__linked_taginfo G__TVirtualReaderDictLN_THEADERClass;
extern G__linked_taginfo G__TVirtualReaderDictLN_TEPICClass;
extern G__linked_taginfo G__TVirtualReaderDictLN_TVirtualReader;

/* STUB derived class for protected member access */
