/********************************************************************
* dicts/Linux64RHEL7/TGsimDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TGsimDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTGsimDict();
extern void G__cpp_setup_inheritanceTGsimDict();
extern void G__cpp_setup_typetableTGsimDict();
extern void G__cpp_setup_memvarTGsimDict();
extern void G__cpp_setup_globalTGsimDict();
extern void G__cpp_setup_memfuncTGsimDict();
extern void G__cpp_setup_funcTGsimDict();
extern void G__set_cpp_environmentTGsimDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TGsim.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TGsimDictLN_TClass;
extern G__linked_taginfo G__TGsimDictLN_TBuffer;
extern G__linked_taginfo G__TGsimDictLN_TMemberInspector;
extern G__linked_taginfo G__TGsimDictLN_TObject;
extern G__linked_taginfo G__TGsimDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TGsimDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TGsimDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGsimDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TGsimDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGsimDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TGsimDictLN_TDatime;
extern G__linked_taginfo G__TGsimDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TGsimDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TGsimDictLN_TVector3;
extern G__linked_taginfo G__TGsimDictLN_TLorentzVector;
extern G__linked_taginfo G__TGsimDictLN_clasHEAD_t;
extern G__linked_taginfo G__TGsimDictLN_clasPART_t;
extern G__linked_taginfo G__TGsimDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TGsimDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TGsimDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TGsimDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TGsimDictLN_THEADERClass;
extern G__linked_taginfo G__TGsimDictLN_TEVNTClass;
extern G__linked_taginfo G__TGsimDictLN_THEADClass;
extern G__linked_taginfo G__TGsimDictLN_TGSIMClass;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TGsimDictLN_TVirtualReader;
extern G__linked_taginfo G__TGsimDictLN_TGsim;

/* STUB derived class for protected member access */
