/********************************************************************
* dicts/Linux64RHEL7/TMCVXClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TMCVXClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMCVXClassDict();
extern void G__cpp_setup_inheritanceTMCVXClassDict();
extern void G__cpp_setup_typetableTMCVXClassDict();
extern void G__cpp_setup_memvarTMCVXClassDict();
extern void G__cpp_setup_globalTMCVXClassDict();
extern void G__cpp_setup_memfuncTMCVXClassDict();
extern void G__cpp_setup_funcTMCVXClassDict();
extern void G__set_cpp_environmentTMCVXClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMCVXClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMCVXClassDictLN_TClass;
extern G__linked_taginfo G__TMCVXClassDictLN_TBuffer;
extern G__linked_taginfo G__TMCVXClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TMCVXClassDictLN_TObject;
extern G__linked_taginfo G__TMCVXClassDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMCVXClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMCVXClassDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TMCVXClassDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TElementActionTlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TElementPosActionTlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TMCVXClassDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_pairlEunsignedsPintcOintgR;
extern G__linked_taginfo G__TMCVXClassDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR;
extern G__linked_taginfo G__TMCVXClassDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTRow_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTRowlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTDiag_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTColumn_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTFlat_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSub_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseRow_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseDiag_constlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTColumnlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTDiaglEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTFlatlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSublEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseRowlEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMatrixTSparseDiaglEdoublegR;
extern G__linked_taginfo G__TMCVXClassDictLN_TMCVXClass;

/* STUB derived class for protected member access */
