/********************************************************************
* dicts/Linux64RHEL6/TTBTRClassDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL6/TTBTRClassDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTTBTRClassDict();
extern void G__cpp_setup_inheritanceTTBTRClassDict();
extern void G__cpp_setup_typetableTTBTRClassDict();
extern void G__cpp_setup_memvarTTBTRClassDict();
extern void G__cpp_setup_globalTTBTRClassDict();
extern void G__cpp_setup_memfuncTTBTRClassDict();
extern void G__cpp_setup_funcTTBTRClassDict();
extern void G__set_cpp_environmentTTBTRClassDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TTBTRClass.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TTBTRClassDictLN_TClass;
extern G__linked_taginfo G__TTBTRClassDictLN_TBuffer;
extern G__linked_taginfo G__TTBTRClassDictLN_TMemberInspector;
extern G__linked_taginfo G__TTBTRClassDictLN_TObject;
extern G__linked_taginfo G__TTBTRClassDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TTBTRClassDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTBTRClassDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TTBTRClassDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TTBTRClassDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TTBTRClassDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TTBTRClassDictLN_TTBTRClass;

/* STUB derived class for protected member access */
