/********************************************************************
* dicts/Linux64RHEL7/TMiniDSTWriterDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error dicts/Linux64RHEL7/TMiniDSTWriterDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTMiniDSTWriterDict();
extern void G__cpp_setup_inheritanceTMiniDSTWriterDict();
extern void G__cpp_setup_typetableTMiniDSTWriterDict();
extern void G__cpp_setup_memvarTMiniDSTWriterDict();
extern void G__cpp_setup_globalTMiniDSTWriterDict();
extern void G__cpp_setup_memfuncTMiniDSTWriterDict();
extern void G__cpp_setup_funcTMiniDSTWriterDict();
extern void G__set_cpp_environmentTMiniDSTWriterDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TMiniDSTWriter.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TMiniDSTWriterDictLN_TClass;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TBuffer;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMemberInspector;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TObject;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TClonesArray;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TFile;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TTree;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TBranch;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMiniDSTClass;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMiniHEADClass;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TGSIMClass;
extern G__linked_taginfo G__TMiniDSTWriterDictLN_TMiniDSTWriter;

/* STUB derived class for protected member access */
