//
// File generated by /u/apps/root/5.34.36/root/bin/rootcint at Fri Feb 24 17:39:19 2017

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dictsdILinux64RHEL7dITClasToolDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TClasToolDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TInterpreter.h"
#include "TVirtualMutex.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOTShadow {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOTShadow
// END OF SHADOWS

namespace ClasTool {
   namespace ROOTDict {
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance();
      static void ClasTool_Dictionary();

      // Function generating the singleton type initializer
      inline ::ROOT::TGenericClassInfo *GenerateInitInstance()
      {
         static ::ROOT::TGenericClassInfo 
            instance("ClasTool", 0 /*version*/, "./TClasTool.h", 112,
                     ::ROOT::DefineBehavior((void*)0,(void*)0),
                     &ClasTool_Dictionary, 0);
         return &instance;
      }
      // Insure that the inline function is _not_ optimized away by the compiler
      ::ROOT::TGenericClassInfo *(*_R__UNIQUE_(InitFunctionKeeper))() = &GenerateInitInstance;  
      // Static variable to force the class initialization
      static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstance(); R__UseDummy(_R__UNIQUE_(Init));

      // Dictionary for non-ClassDef classes
      static void ClasTool_Dictionary() {
         GenerateInitInstance()->GetClass();
      }

   }
}

namespace ROOTDict {
   void TClasTool_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TClasTool(void *p = 0);
   static void *newArray_TClasTool(Long_t size, void *p);
   static void delete_TClasTool(void *p);
   static void deleteArray_TClasTool(void *p);
   static void destruct_TClasTool(void *p);
   static void streamer_TClasTool(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static ROOT::TGenericClassInfo *GenerateInitInstanceLocal(const ::TClasTool*)
   {
      ::TClasTool *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TClasTool >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TClasTool", ::TClasTool::Class_Version(), "./TClasTool.h", 228,
                  typeid(::TClasTool), ::ROOT::DefineBehavior(ptr, ptr),
                  &::TClasTool::Dictionary, isa_proxy, 0,
                  sizeof(::TClasTool) );
      instance.SetNew(&new_TClasTool);
      instance.SetNewArray(&newArray_TClasTool);
      instance.SetDelete(&delete_TClasTool);
      instance.SetDeleteArray(&deleteArray_TClasTool);
      instance.SetDestructor(&destruct_TClasTool);
      instance.SetStreamerFunc(&streamer_TClasTool);
      return &instance;
   }
   ROOT::TGenericClassInfo *GenerateInitInstance(const ::TClasTool*)
   {
      return GenerateInitInstanceLocal((::TClasTool*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TClasTool*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOTDict

//______________________________________________________________________________
atomic_TClass_ptr TClasTool::fgIsA(0);  // static to hold class pointer

//______________________________________________________________________________
const char *TClasTool::Class_Name()
{
   return "TClasTool";
}

//______________________________________________________________________________
const char *TClasTool::ImplFileName()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TClasTool*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TClasTool::ImplFileLine()
{
   return ::ROOTDict::GenerateInitInstanceLocal((const ::TClasTool*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TClasTool::Dictionary()
{
   fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TClasTool*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TClasTool::Class()
{
   if (!fgIsA) { R__LOCKGUARD2(gCINTMutex); if(!fgIsA) {fgIsA = ::ROOTDict::GenerateInitInstanceLocal((const ::TClasTool*)0x0)->GetClass();} }
   return fgIsA;
}

//______________________________________________________________________________
void TClasTool::Streamer(TBuffer &R__b)
{
   // Stream an object of class TClasTool.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      R__b >> fReader;
      R__b >> fDebug_Mode;
      R__b >> fEBeam;
      R__b >> isReaderDefined;
      R__b.CheckByteCount(R__s, R__c, TClasTool::IsA());
   } else {
      R__c = R__b.WriteVersion(TClasTool::IsA(), kTRUE);
      TObject::Streamer(R__b);
      R__b << fReader;
      R__b << fDebug_Mode;
      R__b << fEBeam;
      R__b << isReaderDefined;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TClasTool::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TClasTool.
      TClass *R__cl = ::TClasTool::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fReader", &fReader);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDebug_Mode", &fDebug_Mode);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEBeam", &fEBeam);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "isReaderDefined", &isReaderDefined);
      TObject::ShowMembers(R__insp);
}

namespace ROOTDict {
   // Wrappers around operator new
   static void *new_TClasTool(void *p) {
      return  p ? new(p) ::TClasTool : new ::TClasTool;
   }
   static void *newArray_TClasTool(Long_t nElements, void *p) {
      return p ? new(p) ::TClasTool[nElements] : new ::TClasTool[nElements];
   }
   // Wrapper around operator delete
   static void delete_TClasTool(void *p) {
      delete ((::TClasTool*)p);
   }
   static void deleteArray_TClasTool(void *p) {
      delete [] ((::TClasTool*)p);
   }
   static void destruct_TClasTool(void *p) {
      typedef ::TClasTool current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TClasTool(TBuffer &buf, void *obj) {
      ((::TClasTool*)obj)->::TClasTool::Streamer(buf);
   }
} // end of namespace ROOTDict for class ::TClasTool

/********************************************************
* dicts/Linux64RHEL7/TClasToolDict.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTClasToolDict();

extern "C" void G__set_cpp_environmentTClasToolDict() {
  G__cpp_reset_tagtableTClasToolDict();
}
#include <new>
extern "C" int G__cpp_dllrevTClasToolDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* ClasTool */
static int G__TClasToolDict_804_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClasTool::GetTypeFromPid((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClasTool::GetPidFromType((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ClasTool::GetPartMassID((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ClasTool::GetPartMassIdx((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClasTool::GetPartChargeID((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ClasTool::GetPartChargeIdx((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartNameIdx((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartShortNameIdx((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartName((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartShortName((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartSymbol((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_804_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) ClasTool::GetPartSymbolIdx((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}


/* TClasTool */
static int G__TClasToolDict_805_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TClasTool* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TClasTool[n];
     } else {
       p = new((void*) gvp) TClasTool[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TClasTool;
     } else {
       p = new((void*) gvp) TClasTool;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->Add((const Char_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->AddFile((const Char_t*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->AddEPICFile((const char*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->Check_Reader_Defined());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->Correct_ECPB_bank((TEVNTClass*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->Correct_ECPB_bank((TECPBClass*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetBankRow((const Char_t*) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetCurrentEvent());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TClasTool*) G__getstructoffset())->GetEntries());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TClasTool*) G__getstructoffset())->GetEntriesFast());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TClasTool*) G__getstructoffset())->GetEPICValue((const char*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetEPICClass());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 2:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetEntry((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
      break;
   case 1:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetEntry((Int_t) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetEntry());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetEventNumber());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetHEADER());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetHelicity());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->GetInvariants((Float_t*) G__int(libp->para[0]), (Float_t*) G__int(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetNFiles());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetNotify());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetNPart());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetNRows((const Char_t*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetNRows());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetPartID((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->GetPartCharge((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((TClasTool*) G__getstructoffset())->GetPart3Vector((Int_t) G__int(libp->para[0]));
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TClasTool*) G__getstructoffset())->GetPart4Vector((Int_t) G__int(libp->para[0]));
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TVector3* pobj;
         TVector3 xobj = ((TClasTool*) G__getstructoffset())->GetPartVertex((Int_t) G__int(libp->para[0]));
         pobj = new TVector3(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetVert((Int_t) G__int(libp->para[0]), (Int_t) G__int(libp->para[1])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetReader());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_30(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetTree((Char_t*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetTree());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_31(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->InitDSTReader((const Char_t*) G__int(libp->para[0])));
      break;
   case 0:
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->InitDSTReader());
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->InitDSTReader((TVirtualReader*) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) ((TClasTool*) G__getstructoffset())->Next());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   switch (libp->paran) {
   case 1:
      ((TClasTool*) G__getstructoffset())->Print((Int_t) G__int(libp->para[0]));
      G__setnull(result7);
      break;
   case 0:
      ((TClasTool*) G__getstructoffset())->Print();
      G__setnull(result7);
      break;
   }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->PrintEventStatus();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->PrintEPICPosition();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->SetNotify((TObject*) G__int(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->SetNoScalers();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->SetBeamEnergy((Float_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_40(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 102, (double) ((TClasTool*) G__getstructoffset())->GetBeamEnergy());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_41(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetEVNT((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_42(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) ((TClasTool*) G__getstructoffset())->GetDCPB((Int_t) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_44(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TClasTool::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_45(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TClasTool::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_46(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TClasTool::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_47(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TClasTool::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_51(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TClasTool*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_52(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TClasTool::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_53(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TClasTool::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_54(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TClasTool::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TClasToolDict_805_0_55(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TClasTool::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TClasToolDict_805_0_56(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TClasTool* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TClasTool(*(TClasTool*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TClasTool G__TTClasTool;
static int G__TClasToolDict_805_0_57(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TClasTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TClasTool*) (soff+(sizeof(TClasTool)*i)))->~G__TTClasTool();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TClasTool*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TClasTool*) (soff))->~G__TTClasTool();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TClasToolDict_805_0_58(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TClasTool* dest = (TClasTool*) G__getstructoffset();
   *dest = *(TClasTool*) libp->para[0].ref;
   const TClasTool& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* ClasTool */

/* TClasTool */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTClasToolDict {
 public:
  G__Sizep2memfuncTClasToolDict(): p(&G__Sizep2memfuncTClasToolDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTClasToolDict::*p)();
};

size_t G__get_sizep2memfuncTClasToolDict()
{
  G__Sizep2memfuncTClasToolDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTClasToolDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool))) {
     TClasTool *G__Lderived;
     G__Lderived=(TClasTool*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool),G__get_linked_tagnum(&G__TClasToolDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTClasToolDict() {

   /* Setting up typedef entry */
   G__search_typename2("Char_t",99,-1,0,-1);
   G__setnewtype(-1,"Signed Character 1 byte (char)",0);
   G__search_typename2("Int_t",105,-1,0,-1);
   G__setnewtype(-1,"Signed integer 4 bytes (int)",0);
   G__search_typename2("Float_t",102,-1,0,-1);
   G__setnewtype(-1,"Float 4 bytes (float)",0);
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<std::bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,std::ptrdiff_t,const TObject**,const TObject*&>",117,G__get_linked_tagnum(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*>",117,G__get_linked_tagnum(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long>",117,G__get_linked_tagnum(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("iterator<bidirectional_iterator_tag,TObject*,long,const TObject**>",117,G__get_linked_tagnum(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<UInt_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TString>",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<std::string,TObjArray*>",117,G__get_linked_tagnum(&G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*>",117,G__get_linked_tagnum(&G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("map<string,TObjArray*,less<string> >",117,G__get_linked_tagnum(&G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("pair<UInt_t,Int_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_pairlEunsignedsPintcOintgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<std::pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<UInt_t,Int_t> >",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TClasToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<pair<unsigned int,int> >",117,G__get_linked_tagnum(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTColumn_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTFlat_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSub_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseRow_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseDiag_constlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTColumnlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTFlatlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSublEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseRowlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TMatrixTSparseDiaglEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TElementActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Double_t>",117,G__get_linked_tagnum(&G__TClasToolDictLN_TElementPosActionTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* ClasTool */
static void G__setup_memvarClasTool(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TClasToolDictLN_ClasTool));
   {
   G__memvar_setup((void*)(&ClasTool::fgParticle_Mass),102,0,1,-1,G__defined_typename("Float_t"),-2,1,"fgParticle_Mass[13]=",0,(char*)NULL);
   G__memvar_setup((void*)(&ClasTool::fgParticle_Charge),105,0,1,-1,G__defined_typename("Int_t"),-2,1,"fgParticle_Charge[13]=",0,(char*)NULL);
   G__memvar_setup((void*)(&ClasTool::fgParticle_Id),105,0,1,-1,G__defined_typename("Int_t"),-2,1,"fgParticle_Id[13]=",0,(char*)NULL);
   G__memvar_setup((void*)(&ClasTool::fgParticle_Name),67,0,1,-1,-1,-2,1,"fgParticle_Name[13]=",0,(char*)NULL);
   G__memvar_setup((void*)(&ClasTool::fgParticle_ShortName),67,0,1,-1,-1,-2,1,"fgParticle_ShortName[13]=",0,(char*)NULL);
   G__memvar_setup((void*)(&ClasTool::fgParticle_Symbol),67,0,1,-1,-1,-2,1,"fgParticle_Symbol[13]=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TClasTool */
static void G__setup_memvarTClasTool(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool));
   { TClasTool *p; p=(TClasTool*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fReader)-(long)(p)),85,0,0,G__get_linked_tagnum(&G__TClasToolDictLN_TVirtualReader),-1,-1,1,"fReader=",0,"This is a pointer to the actual reader used.");
   G__memvar_setup((void*)((long)(&p->fDebug_Mode)-(long)(p)),105,0,0,-1,G__defined_typename("Int_t"),-1,1,"fDebug_Mode=",0,"Sets the verbosity of the code. ");
   G__memvar_setup((void*)0,102,0,0,-1,G__defined_typename("Float_t"),-1,2,"fEBeam=",0,"Beam energy. Set with SetBeamEnergy().");
   G__memvar_setup((void*)0,105,0,0,-1,G__defined_typename("Int_t"),-1,2,"isReaderDefined=",0,"True is reader is initialized.");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TClasToolDictLN_TClass),G__defined_typename("atomic_TClass_ptr"),-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTClasToolDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncClasTool(void) {
   /* ClasTool */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TClasToolDictLN_ClasTool));
   G__memfunc_setup("GetTypeFromPid",1395,G__TClasToolDict_804_0_1, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (Int_t (*)(Int_t))(&ClasTool::GetTypeFromPid) ), 0);
   G__memfunc_setup("GetPidFromType",1395,G__TClasToolDict_804_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - type", (char*)NULL, (void*) G__func2void( (Int_t (*)(Int_t))(&ClasTool::GetPidFromType) ), 0);
   G__memfunc_setup("GetPartMassID",1240,G__TClasToolDict_804_0_3, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (Float_t (*)(Int_t))(&ClasTool::GetPartMassID) ), 0);
   G__memfunc_setup("GetPartMassIdx",1392,G__TClasToolDict_804_0_4, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - idx", (char*)NULL, (void*) G__func2void( (Float_t (*)(Int_t))(&ClasTool::GetPartMassIdx) ), 0);
   G__memfunc_setup("GetPartChargeID",1422,G__TClasToolDict_804_0_5, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (Int_t (*)(Int_t))(&ClasTool::GetPartChargeID) ), 0);
   G__memfunc_setup("GetPartChargeIdx",1574,G__TClasToolDict_804_0_6, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - idx", (char*)NULL, (void*) G__func2void( (Int_t (*)(Int_t))(&ClasTool::GetPartChargeIdx) ), 0);
   G__memfunc_setup("GetPartNameIdx",1373,G__TClasToolDict_804_0_7, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - idx", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartNameIdx) ), 0);
   G__memfunc_setup("GetPartShortNameIdx",1901,G__TClasToolDict_804_0_8, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - idx", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartShortNameIdx) ), 0);
   G__memfunc_setup("GetPartName",1080,G__TClasToolDict_804_0_9, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartName) ), 0);
   G__memfunc_setup("GetPartShortName",1608,G__TClasToolDict_804_0_10, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartShortName) ), 0);
   G__memfunc_setup("GetPartSymbol",1325,G__TClasToolDict_804_0_11, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - pid", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartSymbol) ), 0);
   G__memfunc_setup("GetPartSymbolIdx",1618,G__TClasToolDict_804_0_12, 67, -1, -1, 0, 1, 1, 1, 1, "i - 'Int_t' 0 - idx", (char*)NULL, (void*) G__func2void( (const char* (*)(Int_t))(&ClasTool::GetPartSymbolIdx) ), 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTClasTool(void) {
   /* TClasTool */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool));
   G__memfunc_setup("TClasTool",885,G__TClasToolDict_805_0_1, 105, G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Add",265,G__TClasToolDict_805_0_2, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - 'Char_t' 10 - filename", "Add files to the chain in the VirtualReader.", (void*) NULL, 0);
   G__memfunc_setup("AddFile",649,G__TClasToolDict_805_0_3, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - 'Char_t' 10 - filename", "Add a file to the chain in the VirtualReader.", (void*) NULL, 0);
   G__memfunc_setup("AddEPICFile",938,G__TClasToolDict_805_0_4, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"C - - 10 - filename i - 'Int_t' 0 - nentries", "Add a file to the EPIC chain", (void*) NULL, 0);
   G__memfunc_setup("Check_Reader_Defined",1950,G__TClasToolDict_805_0_5, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "Check if Reader is ok.", (void*) NULL, 0);
   G__memfunc_setup("Correct_ECPB_bank",1606,G__TClasToolDict_805_0_6, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TEVNTClass' - 0 - e", "Correct erroneous ECPB entries.", (void*) NULL, 0);
   G__memfunc_setup("Correct_ECPB_bank",1606,G__TClasToolDict_805_0_7, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TECPBClass' - 0 - eco", "Correct erroneous ECPB entries.", (void*) NULL, 0);
   G__memfunc_setup("GetBankRow",980,G__TClasToolDict_805_0_8, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TObject), -1, 0, 2, 1, 1, 0, 
"C - 'Char_t' 10 - bankname i - 'Int_t' 0 - nrow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetCurrentEvent",1541,G__TClasToolDict_805_0_9, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEntries",1018,G__TClasToolDict_805_0_10, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEntriesFast",1416,G__TClasToolDict_805_0_11, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEPICValue",1086,G__TClasToolDict_805_0_12, 102, -1, G__defined_typename("Float_t"), 0, 1, 1, 1, 0, "C - - 10 - fName", "return EPIC value corresponding to fName", (void*) NULL, 0);
   G__memfunc_setup("GetEPICClass",1079,G__TClasToolDict_805_0_13, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TEPICClass), -1, 0, 0, 1, 1, 0, "", "return the current EPICClass. Only gets the currently selected EPIC, to ensure that this is the one corresponding to the current phys event call GetEPICValue", (void*) NULL, 0);
   G__memfunc_setup("GetEntry",818,G__TClasToolDict_805_0_14, 105, -1, G__defined_typename("Int_t"), 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 '-1' entry i - 'Int_t' 0 '0' getall", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEventNumber",1419,G__TClasToolDict_805_0_15, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHEADER",713,G__TClasToolDict_805_0_16, 85, G__get_linked_tagnum(&G__TClasToolDictLN_THEADERClass), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetHelicity",1115,G__TClasToolDict_805_0_17, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetInvariants",1343,G__TClasToolDict_805_0_18, 121, -1, -1, 0, 2, 1, 1, 0, 
"F - 'Float_t' 0 - Q2 F - 'Float_t' 0 - W2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNFiles",865,G__TClasToolDict_805_0_19, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNotify",921,G__TClasToolDict_805_0_20, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TObject), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNPart",773,G__TClasToolDict_805_0_21, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetNRows",793,G__TClasToolDict_805_0_22, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - 'Char_t' 10 '\"EVNT\"' bankname", "return number of items in bank.", (void*) NULL, 0);
   G__memfunc_setup("GetPartID",836,G__TClasToolDict_805_0_23, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - indx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPartCharge",1281,G__TClasToolDict_805_0_24, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "i - 'Int_t' 0 - indx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPart3Vector",1373,G__TClasToolDict_805_0_25, 117, G__get_linked_tagnum(&G__TClasToolDictLN_TVector3), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - indx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPart4Vector",1374,G__TClasToolDict_805_0_26, 117, G__get_linked_tagnum(&G__TClasToolDictLN_TLorentzVector), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - indx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetPartVertex",1333,G__TClasToolDict_805_0_27, 117, G__get_linked_tagnum(&G__TClasToolDictLN_TVector3), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - indx", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetVert",705,G__TClasToolDict_805_0_28, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TVERTClass), -1, 0, 2, 1, 1, 0, 
"i - 'Int_t' 0 - part1 i - 'Int_t' 0 - part2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetReader",883,G__TClasToolDict_805_0_29, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TVirtualReader), -1, 0, 0, 1, 1, 0, "", "Get pointer to reader", (void*) NULL, 0);
   G__memfunc_setup("GetTree",688,G__TClasToolDict_805_0_30, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TChain), -1, 0, 1, 1, 1, 0, "C - 'Char_t' 0 '\"EVNT\"' treename", "Get the actual tree from reader", (void*) NULL, 0);
   G__memfunc_setup("InitDSTReader",1234,G__TClasToolDict_805_0_31, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "C - 'Char_t' 10 '\"ROOTDSTR\"' readertype", "init reader.", (void*) NULL, 0);
   G__memfunc_setup("InitDSTReader",1234,G__TClasToolDict_805_0_32, 105, -1, G__defined_typename("Int_t"), 0, 1, 1, 1, 0, "U 'TVirtualReader' - 0 - reader", "init reader.", (void*) NULL, 0);
   G__memfunc_setup("Next",415,G__TClasToolDict_805_0_33, 105, -1, G__defined_typename("Int_t"), 0, 0, 1, 1, 0, "", "Get the next event.", (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__TClasToolDict_805_0_34, 121, -1, -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 '0' full", "Print information about the current reader.", (void*) NULL, 0);
   G__memfunc_setup("PrintEventStatus",1683,G__TClasToolDict_805_0_35, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("PrintEPICPosition",1667,G__TClasToolDict_805_0_36, 121, -1, -1, 0, 0, 1, 1, 0, "", "Prints the position of the currently selected EPIC in terms of event and run numbers", (void*) NULL, 0);
   G__memfunc_setup("SetNotify",933,G__TClasToolDict_805_0_37, 121, -1, -1, 0, 1, 1, 1, 0, "U 'TObject' - 0 - Notify", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetNoScalers",1206,G__TClasToolDict_805_0_38, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBeamEnergy",1291,G__TClasToolDict_805_0_39, 121, -1, -1, 0, 1, 1, 1, 0, "f - 'Float_t' 0 - fbm", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBeamEnergy",1279,G__TClasToolDict_805_0_40, 102, -1, G__defined_typename("Float_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetEVNT",605,G__TClasToolDict_805_0_41, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TEVNTClass), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - nrow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetDCPB",569,G__TClasToolDict_805_0_42, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TDCPBClass), -1, 0, 1, 1, 1, 0, "i - 'Int_t' 0 - nrow", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Vert_Error_Handler",1831,(G__InterfaceMethod) NULL, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TVERTClass), -1, 0, 3, 1, 2, 0, 
"i - 'Int_t' 0 - NRows i - 'Int_t' 0 - track1 "
"i - 'Int_t' 0 - track2", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TClasToolDict_805_0_44, 85, G__get_linked_tagnum(&G__TClasToolDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TClasTool::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TClasToolDict_805_0_45, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TClasTool::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TClasToolDict_805_0_46, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TClasTool::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TClasToolDict_805_0_47, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TClasTool::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TClasToolDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TClasToolDict_805_0_51, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TClasToolDict_805_0_52, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TClasTool::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TClasToolDict_805_0_53, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TClasTool::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TClasToolDict_805_0_54, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TClasTool::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TClasToolDict_805_0_55, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TClasTool::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TClasTool", 885, G__TClasToolDict_805_0_56, (int) ('i'), G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool), -1, 0, 1, 1, 1, 0, "u 'TClasTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TClasTool", 1011, G__TClasToolDict_805_0_57, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TClasToolDict_805_0_58, (int) ('u'), G__get_linked_tagnum(&G__TClasToolDictLN_TClasTool), -1, 1, 1, 1, 1, 0, "u 'TClasTool' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTClasToolDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {
}

static void G__cpp_setup_global3() {
}

static void G__cpp_setup_global4() {
}

static void G__cpp_setup_global5() {
}

static void G__cpp_setup_global6() {
}

static void G__cpp_setup_global7() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTClasToolDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
  G__cpp_setup_global3();
  G__cpp_setup_global4();
  G__cpp_setup_global5();
  G__cpp_setup_global6();
  G__cpp_setup_global7();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {
}

static void G__cpp_setup_func15() {
}

static void G__cpp_setup_func16() {
}

static void G__cpp_setup_func17() {
}

static void G__cpp_setup_func18() {
}

static void G__cpp_setup_func19() {
}

static void G__cpp_setup_func20() {
}

static void G__cpp_setup_func21() {
}

static void G__cpp_setup_func22() {
}

static void G__cpp_setup_func23() {
}

static void G__cpp_setup_func24() {
}

static void G__cpp_setup_func25() {
}

static void G__cpp_setup_func26() {
}

static void G__cpp_setup_func27() {
}

static void G__cpp_setup_func28() {
}

static void G__cpp_setup_func29() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTClasToolDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
  G__cpp_setup_func15();
  G__cpp_setup_func16();
  G__cpp_setup_func17();
  G__cpp_setup_func18();
  G__cpp_setup_func19();
  G__cpp_setup_func20();
  G__cpp_setup_func21();
  G__cpp_setup_func22();
  G__cpp_setup_func23();
  G__cpp_setup_func24();
  G__cpp_setup_func25();
  G__cpp_setup_func26();
  G__cpp_setup_func27();
  G__cpp_setup_func28();
  G__cpp_setup_func29();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TClasToolDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR = { "vector<unsigned int,allocator<unsigned int> >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR = { "iterator<bidirectional_iterator_tag,TObject*,long,const TObject**,const TObject*&>" , 115 , -1 };
G__linked_taginfo G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR = { "vector<TString,allocator<TString> >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TString,allocator<TString> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR = { "map<string,TObjArray*,less<string>,allocator<pair<const string,TObjArray*> > >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TChain = { "TChain" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_pairlEunsignedsPintcOintgR = { "pair<unsigned int,int>" , 115 , -1 };
G__linked_taginfo G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR = { "vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<pair<unsigned int,int>,allocator<pair<unsigned int,int> > >::iterator>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TElementActionTlEdoublegR = { "TElementActionT<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TElementPosActionTlEdoublegR = { "TElementPosActionT<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_THEADERClass = { "THEADERClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TEVNTClass = { "TEVNTClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TECPBClass = { "TECPBClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TDCPBClass = { "TDCPBClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TEPICClass = { "TEPICClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TVERTClass = { "TVERTClass" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTlEdoublegR = { "TMatrixT<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTRow_constlEdoublegR = { "TMatrixTRow_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTRowlEdoublegR = { "TMatrixTRow<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTDiag_constlEdoublegR = { "TMatrixTDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTColumn_constlEdoublegR = { "TMatrixTColumn_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTFlat_constlEdoublegR = { "TMatrixTFlat_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSub_constlEdoublegR = { "TMatrixTSub_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseRow_constlEdoublegR = { "TMatrixTSparseRow_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseDiag_constlEdoublegR = { "TMatrixTSparseDiag_const<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTColumnlEdoublegR = { "TMatrixTColumn<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTDiaglEdoublegR = { "TMatrixTDiag<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTFlatlEdoublegR = { "TMatrixTFlat<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSublEdoublegR = { "TMatrixTSub<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseRowlEdoublegR = { "TMatrixTSparseRow<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TMatrixTSparseDiaglEdoublegR = { "TMatrixTSparseDiag<double>" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_TVirtualReader = { "TVirtualReader" , 99 , -1 };
G__linked_taginfo G__TClasToolDictLN_ClasTool = { "ClasTool" , 110 , -1 };
G__linked_taginfo G__TClasToolDictLN_TClasTool = { "TClasTool" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTClasToolDict() {
  G__TClasToolDictLN_TClass.tagnum = -1 ;
  G__TClasToolDictLN_TBuffer.tagnum = -1 ;
  G__TClasToolDictLN_TMemberInspector.tagnum = -1 ;
  G__TClasToolDictLN_TObject.tagnum = -1 ;
  G__TClasToolDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR.tagnum = -1 ;
  G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_TChain.tagnum = -1 ;
  G__TClasToolDictLN_pairlEunsignedsPintcOintgR.tagnum = -1 ;
  G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR.tagnum = -1 ;
  G__TClasToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TElementActionTlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TElementPosActionTlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TClasToolDictLN_TVector3.tagnum = -1 ;
  G__TClasToolDictLN_TLorentzVector.tagnum = -1 ;
  G__TClasToolDictLN_THEADERClass.tagnum = -1 ;
  G__TClasToolDictLN_TEVNTClass.tagnum = -1 ;
  G__TClasToolDictLN_TECPBClass.tagnum = -1 ;
  G__TClasToolDictLN_TDCPBClass.tagnum = -1 ;
  G__TClasToolDictLN_TEPICClass.tagnum = -1 ;
  G__TClasToolDictLN_TVERTClass.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTRow_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTRowlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTDiag_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTColumn_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTFlat_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSub_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseRow_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseDiag_constlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTColumnlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTDiaglEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTFlatlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSublEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseRowlEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TMatrixTSparseDiaglEdoublegR.tagnum = -1 ;
  G__TClasToolDictLN_TVirtualReader.tagnum = -1 ;
  G__TClasToolDictLN_ClasTool.tagnum = -1 ;
  G__TClasToolDictLN_TClasTool.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTClasToolDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_vectorlETStringcOallocatorlETStringgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TChain);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_pairlEunsignedsPintcOintgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_vectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_reverse_iteratorlEvectorlEpairlEunsignedsPintcOintgRcOallocatorlEpairlEunsignedsPintcOintgRsPgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TElementActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TElementPosActionTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_THEADERClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TEVNTClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TECPBClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TDCPBClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TEPICClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TVERTClass);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTColumn_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTFlat_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSub_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseRow_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseDiag_constlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTColumnlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTFlatlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSublEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseRowlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TMatrixTSparseDiaglEdoublegR);
   G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TVirtualReader);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TClasToolDictLN_ClasTool),0,-1,0,(char*)NULL,G__setup_memvarClasTool,G__setup_memfuncClasTool);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TClasToolDictLN_TClasTool),sizeof(TClasTool),-1,29952,"Main class for ClasTool package, drives everything else.",G__setup_memvarTClasTool,G__setup_memfuncTClasTool);
}
extern "C" void G__cpp_setupTClasToolDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTClasToolDict()");
  G__set_cpp_environmentTClasToolDict();
  G__cpp_setup_tagtableTClasToolDict();

  G__cpp_setup_inheritanceTClasToolDict();

  G__cpp_setup_typetableTClasToolDict();

  G__cpp_setup_memvarTClasToolDict();

  G__cpp_setup_memfuncTClasToolDict();
  G__cpp_setup_globalTClasToolDict();
  G__cpp_setup_funcTClasToolDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTClasToolDict();
  return;
}
class G__cpp_setup_initTClasToolDict {
  public:
    G__cpp_setup_initTClasToolDict() { G__add_setup_func("TClasToolDict",(G__incsetup)(&G__cpp_setupTClasToolDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTClasToolDict() { G__remove_setup_func("TClasToolDict"); }
};
G__cpp_setup_initTClasToolDict G__cpp_setup_initializerTClasToolDict;

